### ISSUE TITLE
Cauldron 1.7.10 bugg

### ISSUE THREAD

**Issue by Official678** [MinelinkNetwork/CombatTagPlus#112]
Hey! i get this bugg when someone tried to combat log

[21:34:40] [Server thread/ERROR]: Could not pass event PlayerQuitEvent to CombatTagPlus v1.2.3org.bukkit.event.EventExceptionat org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:338) ~[JavaPluginLoader$1.class:KCauldron-1.7.10-2.1403.1.54]at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:KCauldron-1.7.10-2.1403.1.54]at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:507) [SimplePluginManager.class:KCauldron-1.7.10-2.1403.1.54]at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:492) [SimplePluginManager.class:KCauldron-1.7.10-2.1403.1.54]at net.minecraft.server.management.ServerConfigurationManager.disconnect(ServerConfigurationManager.java:431) [oi.class:?]at net.minecraft.network.NetHandlerPlayServer.func_147231_a(NetHandlerPlayServer.java:945) [nh.class:?]at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:166) [nc.class:?]at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:980) [MinecraftServer.class:?]at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:430) [lt.class:?]at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798) [MinecraftServer.class:?]at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658) [MinecraftServer.class:?]at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]Caused by: java.lang.NoSuchMethodError: net.minelink.ctplus.compat.v1_7_R4.NpcPlayer.spawnIn(Lnet/minecraft/world/World;)Vat net.minelink.ctplus.compat.v1_7_R4.NpcPlayerHelperImpl.spawn(NpcPlayerHelperImpl.java:48) ~[?:?]at net.minelink.ctplus.NpcManager.spawn(NpcManager.java:36) ~[?:?]at net.minelink.ctplus.listener.NpcListener.spawnNpc(NpcListener.java:62) ~[?:?]at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_112]at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_112]at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_112]at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_112]at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:334) ~[JavaPluginLoader$1.class:KCauldron-1.7.10-2.1403.1.54]... 11 more

**Comment by Byteflux** [comment]
We do not support your server brand. Only CraftBukkit and Spigot are supported.
