### ISSUE TITLE
API teleport NPC

### ISSUE THREAD

**Issue by Horld3n** [MinelinkNetwork/CombatTagPlus#79]
Hi ! 
I'm creating an ehancement for the HCFactions plugin, and i'm usign your (wonderfull) plugin's API. But I have a problem, I'm not able to teleport a NPC who's created by the plugin. Would you be able to add this to the API ? Or explain how I can do this. 
Thank you !

**Comment by Techcable** [comment]
`getBukkitEntity().teleport(location)` doesn't work?

**Comment by Horld3n** [comment]
It throw a Null Pointer Exception

**Comment by Techcable** [comment]
May I see it?

**Comment by Horld3n** [comment]
http://hastebin.com/hefurupote.avrasm

**Comment by Techcable** [comment]
Where is your stacktrace?
Also, can you gist the _whole_ class?

**Comment by Horld3n** [comment]
http://hastebin.com/ocerulefoy.avrasm
http://hastebin.com/irocozotaq.avrasm

**Comment by Techcable** [comment]
The issue is with [your class](https://gist.github.com/anonymous/07f579c85e4e1e3691d79ac089600e99).
A faction's home returned by `FPlayer.getFaction().getHome()` can be null, so you need to insert a null-check.
Since the faction's home location is null, it throws the NPE:

```
[22:09:41] [Server thread/WARN]: [FactionsAddOn] Task #1685 for FactionsAddOn v1.0 generated an exception
java.lang.NullPointerException
    at org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer.teleport(CraftPlayer.java:464) ~[spigot-1.8.jar:git-Spigot-5818108-db5fd9c]
    at fr.nakitsuro.faddon.pillage.NPCHandler$1.run(NPCHandler.java:34) ~[?:?]
    at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.8.jar:git-Spigot-5818108-db5fd9c]
    at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.8.jar:git-Spigot-5818108-db5fd9c]
    at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:726) [spigot-1.8.jar:git-Spigot-5818108-db5fd9c]
    at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:368) [spigot-1.8.jar:git-Spigot-5818108-db5fd9c]
    at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:657) [spigot-1.8.jar:git-Spigot-5818108-db5fd9c]
    at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:560) [spigot-1.8.jar:git-Spigot-5818108-db5fd9c]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_91]
```
